export const baseUrl = "https://atn.test.acviss.co/";
export const dummyData = [
  {
    brandName: "Brand A",
    batchCode: "B001",
    serialNumber: "SN001",
    message: "Valid",
    userName: "John Doe",
    mobile: "123-456-7890",
    productName: "Benivia",
    sku: "90ml",
    attempts: 1,
    location: "Location A",
    scannedDate: "2023-01-01",
    appName: "App X",
  },
  {
    brandName: "Brand B",
    batchCode: "B002",
    serialNumber: "SN002",
    message: "In Valid",
    userName: "Jane Smith",
    mobile: "987-654-3210",
    attempts: 2,
    location: "Location B",
    productName: "Benivia",
    sku: "240ml",
    scannedDate: "2023-01-02",
    appName: "App Y",
  },
  {
    brandName: "Brand C",
    batchCode: "B003",
    serialNumber: "SN003",
    message: "Valid",
    userName: "Bob Johnson",
    mobile: "555-123-4567",
    sku: "10ml",
    productName: "Coragen",
    attempts: 3,
    location: "Location C",
    scannedDate: "2023-01-03",
    appName: "App Z",
  },
  {
    brandName: "Brand D",
    batchCode: "B004",
    serialNumber: "SN004",
    message: "In Valid",
    userName: "Alice Johnson",
    sku: "30ml",
    productName: "Coragen",
    mobile: "555-987-6543",
    attempts: 4,
    location: "Location D",
    scannedDate: "2023-01-04",
    appName: "App W",
  },
  {
    brandName: "Brand E",
    batchCode: "B005",
    serialNumber: "SN005",
    message: "Valid",
    userName: "Charlie Brown",
    mobile: "777-555-1234",
    productName: "Benivia",
    sku: "90ml",
    attempts: 5,
    location: "Location E",
    scannedDate: "2023-01-05",
    appName: "App V",
  },
  {
    brandName: "Brand AA",
    batchCode: "B026",
    serialNumber: "SN026",
    message: "In Valid",
    userName: "Eva Johnson",
    mobile: "555-123-9876",
    attempts: 2,
    sku: "10ml",
    productName: "Coragen",
    location: "Location AA",
    scannedDate: "2023-01-26",
    appName: "App AB",
  },
  {
    brandName: "Brand BB",
    batchCode: "B027",
    serialNumber: "SN027",
    message: "Valid",
    userName: "Frank Johnson",
    mobile: "555-987-6543",
    productName: "Benivia",
    sku: "240ml",
    attempts: 2,
    location: "Location BB",
    scannedDate: "2023-01-27",
    appName: "App BC",
  },

  {
    brandName: "Brand CC",
    batchCode: "B028",
    serialNumber: "SN028",
    message: "In Valid",
    userName: "Grace Brown",
    mobile: "777-555-1234",
    attempts: 2,
    productName: "Benivia",
    sku: "90ml",
    location: "Location CC",
    scannedDate: "2023-01-28",
    appName: "App CD",
  },
  {
    brandName: "Brand DD",
    batchCode: "B029",
    serialNumber: "SN029",
    message: "Valid",
    userName: "Harry Smith",
    mobile: "987-654-3210",
    attempts: 2,
    sku: "30ml",
    productName: "Coragen",
    location: "Location DD",
    scannedDate: "2023-01-29",
    appName: "App DE",
  },
  {
    brandName: "Brand EE",
    batchCode: "B030",
    serialNumber: "SN030",
    message: "In Valid",
    userName: "Isabel Doe",
    mobile: "123-456-7890",
    attempts: 3,
    productName: "Coragen",
    sku: "10ml",
    location: "Location EE",
    scannedDate: "2023-01-30",
    appName: "App EF",
  },
];
